### ISSUE TITLE
LuaTeX errors not showing

### ISSUE THREAD

**Issue by iclukas** [speedata/publisher#215] opened 2018-12-18 13:15 UTC
When LuaTeX encounters an internal error, sp just outputs “Error executing sdluatex”, which is not very helpful. Maybe there’s some way to show the original error message.

I had this issue on a system with no locales (PHP-FPM). LuaTeX 1.0.8 requires at least LC_ALL to be set, but I think it really doesn’t matter because sp uses its own language settings. Maybe this requirement could be dropped, as it’s not needed when `--luaonly` is active. I think sp could supply a default LC_ALL, just in case.

**Comment by pgundlach** [comment] 2018-12-21 09:18
Which OS? Do you know if this is the case with LuaTeX 1.0.7? I have tried with Mac/Ltx 1.0.7 and I don't need to set `LC_ALL`.

Do you think that setting the `LC_ALL` to `C` is safe?

**Comment by pgundlach** [comment] 2018-12-21 10:41
And for the error messages: I am not sure how to show/hide the error message from LuaTeX. All my tests (not found executable, wrong arguments,..) were reported. Do you have a setup which shows the lack of error messages?

**Comment by iclukas** [comment] 2018-12-21 12:12
OS is Debian Stretch, but it doesn’t matter because PHP-FPM environments usually have zero env vars set, unless explicitly defined in their config. It’s a bit tough to reproduce in a normal environment. But I can confirm that setting `LC_ALL` to `C` works fine.
I just tried 3.5.9 and 3.5.10 on a clean Debian image from https://www.osboxes.org/debian/
To reproduce, I uninstalled the `locale` package and rebooted. 3.5.10 now runs fine and 3.5.9 exits with status 1 and `publisher.status` just contains “Error executing sdluatex”.

I also just noticed that I have 1.0.7 installed. But I found the `LC_ALL` check in 1.0.8’s source, it’s in line 963 of `source/texk/web2c/luatexdir/lua/luainit.c`. So maybe all `fprintf(stderr, "...")` output goes missing.

**Comment by pgundlach** [comment] 2018-12-21 12:19
Could you try with the latest 3.5.10? I have set `LC_ALL` to `C`. 

And for the error output: stdout from LuaTeX is mapped to stdout from the sp command and the same with stderr. They will not end up in the log file though.

**Comment by iclukas** [comment] 2018-12-21 13:08
> Could you try with the latest 3.5.10? I have set `LC_ALL` to `C`.

I did, see above. 

> And for the error output: stdout from LuaTeX is mapped to stdout from the sp command and the same with stderr. They will not end up in the log file though.

It seems like the mapping doesnt’t work, the errors don’t show on the console, even with `--verbose`.

**Comment by pgundlach** [comment] 2018-12-21 22:48
Sorry, I have missed the part with 3.5.10.

So as I understand the only problem that remains is the missing error message from LuaTeX?

**Comment by pgundlach** [comment] 2018-12-21 23:00
I cannot reproduce the problem with the error messages.

Say I have added an unknown command line in the call to sdluatex. I get the error from LuaTeX:

```
$ sp 1>/dev/null 
Run speedata publisher
/Users/patrick/...../sdluatex: unrecognized option '--asdfasdf'
Total run time: 303.594362ms
```

which comes either from `texlua.c` or from `luainit.c`, both use `fprintf(stderr...`. 

I don't know what to do about that.

**Comment by pgundlach** [comment] 2018-12-21 23:01
... one thing that comes into my mind: The output of stderr might not be synchronized. So that the output from LuaTeX doesn't appear where it should be.

**Comment by pgundlach** [comment] 2019-01-21 18:06
I am closing this, as I don't know what to do. You can re-open it of course.

**Closed as completed by pgundlach** 2019-01-21 18:06 UTC
Labels: Feature Request
